kind = "web"
previewPath = "/"
title = "ThisIsArtElias"
version = "1.0.0"
id = "artifacts/thisisartelias"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19266

[services.development]
run = "pnpm --filter @workspace/thisisartelias run dev"

[services.production]
serve = "static"
publicDir = "artifacts/thisisartelias"

[services.env]
PORT = "19266"
BASE_PATH = "/"
